---
title: netrankr - Analyzing Partial Rankings in Networks
format:
  html:
    embed-resources: true
  gfm: default
---

## Description

<!-- - Provide a brief and clear description of the method, its purpose, and what it aims to achieve. Add a link to a related paper from social science domain and show how your method can be applied to solve that research question.   -->

Implements methods for centrality related analyses of networks. 
While the package includes the possibility to build more than 20 indices, 
its main focus lies on index-free assessment of centrality via partial 
rankings obtained by neighborhood-inclusion or positional dominance. These 
partial rankings can be analyzed with different methods, including 
probabilistic methods like computing expected node ranks and relative 
rank probabilities (how likely is it that a node is more central than another?).
The methodology is described in depth in the vignettes and in
Schoch (2018) [<doi:10.1016/j.socnet.2017.12.003>](https://doi.org/10.1016/j.socnet.2017.12.003).

## Keywords

<!-- EDITME -->

* Network Analysis 
* Network Centrality
* Node Rankings

## Science Usecase(s)

Network centrality allows to pinpoint influential or strategically positioned individuals within a social network, offering insights into power dynamics, information flow, and social influence. For example, in studying the spread of health-related information on a platform like Twitter, researchers could use centrality metrics to identify which users are most crucial in disseminating information about a public health campaign. Degree centrality can reveal which individuals have the highest number of direct connections, suggesting they are well-positioned to rapidly broadcast messages. Betweenness centrality highlights users who act as bridges between different groups, making them pivotal for connecting otherwise separate sub-communities and potentially influencing diverse audiences. Closeness centrality identifies individuals who can quickly access or share information throughout the network, often making them efficient distributors of critical updates. By examining these metrics, one can identify not only the main influencers in a network but also potential "gatekeepers" or "brokers" who control or facilitate the flow of information, which is particularly valuable for understanding and optimizing the spread of public health messages or assessing the reach and impact of digital campaigns.

## Repository structure

This repository follows [the standard structure of an R package](https://cran.r-project.org/doc/FAQ/R-exts.html#Package-structure).

## Environment Setup

With R installed:

```r
install.packages("netrankr")
```

<!-- ## Hardware Requirements (Optional) -->
<!-- - The hardware requirements may be needed in specific cases when a method is known to require more memory/compute power.  -->
<!-- - The method need to be executed on a specific architecture (GPUs, Hadoop cluster etc.) -->


## Input Data 

<!-- - The input data has to be a Digital Behavioral Data (DBD) Dataset -->
<!-- - You can provide link to a public DBD dataset. GESIS DBD datasets (https://www.gesis.org/en/institute/digital-behavioral-data) -->

<!-- This is an example -->

`netrankr` accepts network objects in the `igraph` format.

## Sample Input and Output Data

The package comes with sample data that can be used to test all methods.
An example use case can be found [here](https://schochastics.github.io/netrankr/articles/use_case.html).


## How to Use

The package comes with a set of vignettes that describe several use case scenarios.
Please refer to the [overview of this package](https://schochastics.github.io/netrankr/).

## Contact Details

Maintainer: David Schoch <david@schochastics.net>

Issue Tracker: [https://github.com/schochastics/netrankr/issues](https://github.com/schochastics/netrankr/issues)

<!-- ## Publication -->
<!-- - Include information on publications or articles related to the method, if applicable. -->

<!-- ## Acknowledgements -->
<!-- - Acknowledgements if any -->

<!-- ## Disclaimer -->
<!-- - Add any disclaimers, legal notices, or usage restrictions for the method, if necessary. -->
