# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkPairs <- function(x, y) {
    .Call('netrankr_checkPairs', PACKAGE = 'netrankr', x, y)
}

dependency <- function(adj) {
    .Call('netrankr_dependency', PACKAGE = 'netrankr', adj)
}

LatticeOfIdeals <- function(child, parent, Ek, nElem, nIdeals) {
    .Call('netrankr_LatticeOfIdeals', PACKAGE = 'netrankr', child, parent, Ek, nElem, nIdeals)
}

listingIdeals <- function(P, nElem, nIdeals) {
    .Call('netrankr_listingIdeals', PACKAGE = 'netrankr', P, nElem, nIdeals)
}

nialgo <- function(adjList, deg) {
    .Call('netrankr_nialgo', PACKAGE = 'netrankr', adjList, deg)
}

matdom <- function(A, map, benefit) {
    .Call('netrankr_matdom', PACKAGE = 'netrankr', A, map, benefit)
}

rankings <- function(paths, ideals, nRank, nElem) {
    .Call('netrankr_rankings', PACKAGE = 'netrankr', paths, ideals, nRank, nElem)
}

rankprobs <- function(ImPred, ideals, nElem, nIdeals) {
    .Call('netrankr_rankprobs', PACKAGE = 'netrankr', ImPred, ideals, nElem, nIdeals)
}

resistanceDistance <- function(C, n) {
    .Call('netrankr_resistanceDistance', PACKAGE = 'netrankr', C, n)
}

treeOfIdeals <- function(imPred) {
    .Call('netrankr_treeOfIdeals', PACKAGE = 'netrankr', imPred)
}

